TARGETS = pcg32-demo pcg32-global-demo pcg32x2-demo pcg64-demo 

CPPFLAGS += -I.
CFLAGS   += -std=c99 -Wall -Wextra

all: pcg64-challenge pcg64s-challenge

clean:
	rm -f *.o pcg64-challenge pcg64s-challenge

